name: Rust

on:
  workflow_dispatch:
  push:
    branches: 
      -  "master"
      -  "temp"
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-on-macos:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-on-windows:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: |
        choco install nasm
        echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
